#!/bin/bash -l

#SBATCH -J 20_RT_1
#SBATCH --nodes=1
#SBATCH --exclusive
#SBATCH --partition=big
#SBATCH --ntasks=64 
#SBATCH --time=200:00:00
#SBATCH --output=t.out.%j
#SBATCH --error=t.err.%j
#SBATCH --mail-user=joana.bustamante@bam.de
#SBATCH--mail-type=ALL

conda activate Minikappa
python get_minikappa.py
